name: Target Multiple Node.js Versions and Operating Systems
on: [push]

# on:
#   schedule:
#     - # Runs at 02:00 UTC every day
#     - cron: "0 2 * * *"
  

jobs:
  build:
    name: Run Tests Across Node.js Versions and Operating Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Run TestCafe Tests
              - name: Install packages;
        run: npm i
      - name: Run tests
        run: npm t
