name: Basic TestCafe Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository code under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Install packages;
        run: npm i
      - name: Run tests
        run: npm t
#       - name: Install TestCafe from 'npm' and Run Tests
#         uses: DevExpress/testcafe-action@latest
#         with:
#           args: "chrome my-fixture.js"

      # Runs a set of commands using the runners shell
      - name: After tests do something
        run: |
          echo Tests are run,
          echo Cleaning up...;
